version: '1'

services:
  db:
    image: 'postgres:13.1-alpine'
    ports:
      - 5433:5432
    container_name: order_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=order